CREATE TABLE IF NOT EXISTS "accidents" (
	"accident_no" text PRIMARY KEY NOT NULL,
	"accident_date" date NOT NULL,
	"accident_time" time NOT NULL,
	"accident_type" text NOT NULL,
	"severity" text NOT NULL,
	"speed_zone" text NOT NULL,
	"road_name" text NOT NULL,
	"road_type" text NOT NULL,
	"lga_name" text NOT NULL,
	"latitude" real NOT NULL,
	"longitude" real NOT NULL,
	"vicgrid_x" real NOT NULL,
	"vicgrid_y" real NOT NULL,
	"bicyclist" integer NOT NULL,
	"serious_injury" integer NOT NULL,
	"other_injury" integer NOT NULL,
	"non_injured" integer NOT NULL,
	"fatality" integer NOT NULL
);
